#include "pch.h"
#include "ContentReport.h"

#include "ContentCatalog.h"
#include "GameplayCatalog.h"
#include "RewardPresentation.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <set>
#include <sstream>

namespace
{
	std::string StageKind(const StageDefinition& stage)
	{
		return stage.isBoss ? "Boss" : "Battle";
	}

	std::size_t CountMovingPegs(const StageDefinition& stage) noexcept
	{
		return static_cast<std::size_t>(std::count_if(
			stage.pegLayout.pegs.begin(),
			stage.pegLayout.pegs.end(),
			[](const PegDefinition& peg) { return peg.motion.IsMoving(); }));
	}

	std::size_t CountPegs(const StageDefinition& stage, PegType type) noexcept
	{
		return static_cast<std::size_t>(std::count_if(
			stage.pegLayout.pegs.begin(),
			stage.pegLayout.pegs.end(),
			[type](const PegDefinition& peg) { return peg.type == type; }));
	}

	float TotalEnemyHealth(const StageDefinition& stage) noexcept
	{
		float total = 0.0f;
		for (const EnemyDefinition& enemy : stage.enemies) total += enemy.health;
		return total;
	}

	float PreviewThreat(const StageDefinition& stage) noexcept
	{
		const float expectedAttackTurns = stage.rules.playerDamage <= 0.0f
			? 0.0f
			: TotalEnemyHealth(stage) / stage.rules.playerDamage;
		return expectedAttackTurns
			+ static_cast<float>(stage.enemies.size()) * 0.75f
			+ static_cast<float>(CountMovingPegs(stage)) * 0.20f
			+ (stage.isBoss ? 2.0f : 0.0f);
	}

	std::string EscapeCell(std::string value)
	{
		std::replace(value.begin(), value.end(), '|', '/');
		std::replace(value.begin(), value.end(), '\n', ' ');
		return value;
	}
}

ContentReportResult GenerateContentReport(
	const std::filesystem::path& stageCatalogPath,
	const std::filesystem::path& gameplayCatalogPath,
	const std::filesystem::path& outputPath)
{
	ContentReportResult result;
	ContentLoadResult stages = LoadContentCatalog(stageCatalogPath);
	if (!stages.UsedExternalContent())
	{
		result.message = "Stage catalog validation failed at line "
			+ std::to_string(stages.errorLine) + ".";
		return result;
	}
	GameplayCatalogLoadResult gameplay = LoadGameplayCatalog(gameplayCatalogPath, stages.stages);
	if (!gameplay.UsedExternalContent())
	{
		result.message = "Gameplay catalog validation failed at line "
			+ std::to_string(gameplay.errorLine) + ".";
		return result;
	}
	if (!ActivateGameplayCatalog(gameplay, stages.stages))
	{
		result.message = "Validated gameplay catalog could not be activated.";
		return result;
	}

	std::set<std::string> uniqueEnemies;
	for (const StageDefinition& stage : stages.stages)
	{
		result.pegCount += stage.pegLayout.pegs.size();
		result.movingPegCount += CountMovingPegs(stage);
		result.refreshPegCount += CountPegs(stage, PegType::Refresh);
		for (const EnemyDefinition& enemy : stage.enemies) uniqueEnemies.insert(enemy.id);
	}
	result.stageCount = stages.stages.size();
	result.enemyCount = uniqueEnemies.size();
	result.orbCount = gameplay.catalog.progression.orbs.size();
	result.relicCount = gameplay.catalog.progression.relics.size();

	std::error_code directoryError;
	if (!outputPath.parent_path().empty())
	{
		std::filesystem::create_directories(outputPath.parent_path(), directoryError);
		if (directoryError)
		{
			result.message = "Report output directory could not be created.";
			return result;
		}
	}
	std::ofstream report(outputPath, std::ios::binary | std::ios::trunc);
	if (!report)
	{
		result.message = "Report output file could not be opened.";
		return result;
	}

	report << "# Peglin Content Validation Report\n\n"
		<< "> Generated by the authoritative C++ catalog loaders. Preview threat is a design comparison index, not runtime damage.\n\n"
		<< "## Validation Summary\n\n"
		<< "| Check | Result |\n| --- | --- |\n"
		<< "| Stage schema, encoding and bounds | PASS |\n"
		<< "| Gameplay effect and enemy references | PASS |\n"
		<< "| Stages | " << result.stageCount << " |\n"
		<< "| Pegs / moving / Refresh | " << result.pegCount << " / "
		<< result.movingPegCount << " / " << result.refreshPegCount << " |\n"
		<< "| Unique enemies / orbs / relics | " << result.enemyCount << " / "
		<< result.orbCount << " / " << result.relicCount << " |\n\n"
		<< "## Stage Preview\n\n"
		<< "| ID | Name | Kind | Pegs | Moving | Refresh | Enemies | Enemy HP | Player Damage | Threat |\n"
		<< "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n";
	report << std::fixed << std::setprecision(2);
	for (const StageDefinition& stage : stages.stages)
	{
		report << "| " << EscapeCell(stage.id)
			<< " | " << EscapeCell(stage.displayName)
			<< " | " << StageKind(stage)
			<< " | " << stage.pegLayout.pegs.size()
			<< " | " << CountMovingPegs(stage)
			<< " | " << CountPegs(stage, PegType::Refresh)
			<< " | " << stage.enemies.size()
			<< " | " << TotalEnemyHealth(stage)
			<< " | " << stage.rules.playerDamage
			<< " | " << PreviewThreat(stage) << " |\n";
	}

	report << "\n## Enemy References\n\n| ID | Name | HP | Damage Taken | Range |\n"
		<< "| --- | --- | ---: | ---: | ---: |\n";
	std::set<std::string> writtenEnemies;
	for (const StageDefinition& stage : stages.stages)
	{
		for (const EnemyDefinition& enemy : stage.enemies)
		{
			if (!writtenEnemies.insert(enemy.id).second) continue;
			report << "| " << EscapeCell(enemy.id)
				<< " | " << EscapeCell(enemy.displayName)
				<< " | " << enemy.health
				<< " | x" << enemy.damageTakenMultiplier
				<< " | " << enemy.attackRangeCells << " |\n";
		}
	}

	report << "\n## Orb Preview\n\n| ID | Name | Exact Effect |\n| --- | --- | --- |\n";
	for (const OrbDefinition& orb : gameplay.catalog.progression.orbs)
	{
		report << "| " << EscapeCell(orb.id) << " | " << EscapeCell(orb.displayName)
			<< " | " << EscapeCell(DescribeOrbEffect(orb)) << " |\n";
	}
	report << "\n## Relic Preview\n\n| ID | Name | Exact Effect |\n| --- | --- | --- |\n";
	for (const RelicDefinition& relic : gameplay.catalog.progression.relics)
	{
		report << "| " << EscapeCell(relic.id) << " | " << EscapeCell(relic.displayName)
			<< " | " << EscapeCell(DescribeRelicEffect(relic)) << " |\n";
	}
	report.flush();
	if (!report)
	{
		result.message = "Report output failed while writing.";
		return result;
	}

	result.success = true;
	result.message = "Content report generated: " + outputPath.string();
	return result;
}
